# Generated by Django 2.1.7 on 2019-03-18 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_id', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'barcode',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('category_name', models.CharField(max_length=50)),
                ('subcategory_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('order_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order_delivery_date', models.DateField()),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=50)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete='CASCADE', to='stock.Category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('supplier_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=12)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(on_delete='CASCADE', to='stock.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete='CASCADE', to='stock.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_id',
            field=models.ForeignKey(on_delete='CASCADE', to='stock.Supplier'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='product_id',
            field=models.ForeignKey(on_delete='CASCADE', to='stock.Product'),
        ),
    ]
